# Generated by Django 5.1.5 on 2025-02-17 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp3file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='pdf.mp3file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='pdf.profile')),
            ],
        ),
    ]
