# Generated by Django 5.1.5 on 2025-02-18 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='mp3file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp3s', to='pdf.mp3file'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav', to='pdf.profile'),
        ),
    ]
